title: "Caleb Karr" # your name (or website title) here
logo: "images/786af0d7-f5aa-402b-86cb-dea0ae7bda97.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  "Currently, I am the Director/ Senior Project Coordinator for a research center at the University of Oklahoma."
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
